name: Teste Cron Job

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar teste
        run: |
          echo "Executando teste periódico: $(date)"
